version: "3.9"
services:
  cloud-album-api:
    build: .
    restart: always
    image: cloud-album-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      API_KEY: ${API_KEY}
      GOOGLE_DRIVE_ROOT_FILE_ID: ${GOOGLE_DRIVE_ROOT_FILE_ID}
      GOOGLE_DRIVE_SECRET: ${GOOGLE_DRIVE_SECRET}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_SCHEME: ${MONGO_SCHEME}
    command: uvicorn cloud_album_api.main:app --host 0.0.0.0 --reload
  cloud-album-mongo:
    image: mongo:4.4-rc-focal
    volumes:
      - type: bind
        source: ./.data
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
