apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-album-api
  name: cloud-album-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cloud-album-api
  strategy: {}
  template:
    metadata:
      labels:
        app: cloud-album-api
    spec:
      serviceAccountName: ghcr
      containers:
      - image: ghcr.io/0kate/cloud-album-api:latest
        name: cloud-album-api
        resources: {}
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: cloud-album-mongodb-credentials
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloud-album-mongodb-credentials
              key: MONGO_INITDB_ROOT_PASSWORD
        envFrom:
        - configMapRef:
            name: google-drive-root-file-id
        - secretRef:
            name: cloud-album-api-key
        - secretRef:
            name: google-drive-secret
