apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-album-api
  name: cloud-album-api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: cloud-album-api
status:
  loadBalancer: {}
