name: Docker Image CI
on:
  push:
    branches: [ main ]
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: us.gcr.io/${{ secrets.GCP_PROJECT }}/cloud-album-api:latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: GCP Authentication
      uses: google-github-actions/setup-gcloud@master
      with:
        servier_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet
    - name: Build a docker image
      run: docker build . -t $IMAGE
    - name: Push the docker image
      run: docker push $IMAGE
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy cloud-album-api \
          --image $IMAGE \
          --project $GCP_PROJECT \
          --region $GCP_REGION \
          --platform managed \
          --quiet
