name: Docker Image CI
on:
  push:
    branches: [ main ]
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  SERVICE: cloud-album-api
  IMAGE: us.gcr.io/${{ secrets.GCP_PROJECT }}/cloud-album-api:${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.GCP_PROJECT }}

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker

    - name: Build a docker image
      run: docker build . -t ${{ env.IMAGE }}

    - name: Push the docker image
      run: docker push ${{ env.IMAGE }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.SERVICE }}
        image: ${{ env.IMAGE }}
        region: ${{ env.GCP_REGION }}
